name: book_tracker
description: A Letterboxd-style book tracking app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.10
  cloud_firestore: ^5.6.12
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Routing
  go_router: ^14.8.1
  
  # Hooks
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  
  # Network & API
  http: ^1.4.0
  dio: ^5.8.0+1
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  
  # UI
  cached_network_image: ^3.4.1
  
  # Authentication
  google_sign_in: ^6.3.0
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
