// Mocks generated by Mockito 5.4.5 from annotations
// in book_tracker/test/clean_architecture/books_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:book_tracker/features/books/domain/entities/book_entity.dart'
    as _i6;
import 'package:book_tracker/features/books/domain/failures.dart' as _i5;
import 'package:book_tracker/features/books/domain/repositories/book_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookRepository extends _i1.Mock implements _i3.BookRepository {
  MockBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>
      getFeaturedBooks() => (super.noSuchMethod(
            Invocation.method(
              #getFeaturedBooks,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
              this,
              Invocation.method(
                #getFeaturedBooks,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>> searchBooks({
    required String? query,
    String? category,
    String? author,
    List<String>? genres,
    int? page,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBooks,
          [],
          {
            #query: query,
            #category: category,
            #author: author,
            #genres: genres,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
          this,
          Invocation.method(
            #searchBooks,
            [],
            {
              #query: query,
              #category: category,
              #author: author,
              #genres: genres,
              #page: page,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.BookEntity>> getBookById(
          String? bookId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [bookId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.BookEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.BookEntity>(
          this,
          Invocation.method(
            #getBookById,
            [bookId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.BookEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>> getBooksByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooksByCategory,
          [category],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
          this,
          Invocation.method(
            #getBooksByCategory,
            [category],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>
      getTrendingBooks() => (super.noSuchMethod(
            Invocation.method(
              #getTrendingBooks,
              [],
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
              this,
              Invocation.method(
                #getTrendingBooks,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>> getRecommendedBooks(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecommendedBooks,
          [userId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
          this,
          Invocation.method(
            #getRecommendedBooks,
            [userId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>> getBooksByGenre(
          String? genre) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooksByGenre,
          [genre],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
          this,
          Invocation.method(
            #getBooksByGenre,
            [genre],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>> getBooksByAuthor(
          String? author) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooksByAuthor,
          [author],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
          this,
          Invocation.method(
            #getBooksByAuthor,
            [author],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>
      getRecentlyAddedBooks({int? limit = 10}) => (super.noSuchMethod(
            Invocation.method(
              #getRecentlyAddedBooks,
              [],
              {#limit: limit},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                    _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
              this,
              Invocation.method(
                #getRecentlyAddedBooks,
                [],
                {#limit: limit},
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>> getPopularBooks(
          {int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularBooks,
          [],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.BookEntity>>(
          this,
          Invocation.method(
            #getPopularBooks,
            [],
            {#limit: limit},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BookEntity>>>);
}
